# Generated by Django 3.2.8 on 2021-11-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
    ]
